# Configuration for the Blunderbuss GitHub app. For more info see
# https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss
assign_issues:
  - michaelpri10
assign_prs:
  - michaelpri10
assign_prs_by:
- labels:
  - samples
  to:
  - googleapis/java-samples-reviewers