bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - releaseType: java-lts
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 1.111.0-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.114.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.116.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.117.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.120.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.121.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.123.x
