bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - releaseType: java-lts
    bumpMinorPreMajor: true
    branch: 1.111.0-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
