bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
    - releaseType: java-lts
      branch: 1.111.0-sp
    - branch: java7
    - releaseType: java-backport
      branch: 1.114.x
    - releaseType: java-backport
      branch: 1.116.x
    - releaseType: java-backport
      branch: 1.117.x
    - releaseType: java-backport
      branch: 1.120.x
    - releaseType: java-backport
      branch: 1.121.x
    - releaseType: java-backport
      branch: 1.123.x
    - releaseType: java-backport
      branch: 1.125.x
    - releaseType: java-backport
      branch: 1.129.x
    - releaseType: java-backport
      branch: 1.137.x
    - releaseType: java-backport
      branch: 1.140.x
