// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/pubsub/v1/pubsub.proto
// Protobuf Java Version: 4.33.0

package com.google.pubsub.v1;

@com.google.protobuf.Generated
public interface DeleteSnapshotRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.DeleteSnapshotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. Identifier. The name of the snapshot to delete.
   * Format is `projects/{project}/snapshots/{snap}`.
   * </pre>
   *
   * <code>
   * string snapshot = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IDENTIFIER, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The snapshot.
   */
  java.lang.String getSnapshot();

  /**
   *
   *
   * <pre>
   * Required. Identifier. The name of the snapshot to delete.
   * Format is `projects/{project}/snapshots/{snap}`.
   * </pre>
   *
   * <code>
   * string snapshot = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IDENTIFIER, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for snapshot.
   */
  com.google.protobuf.ByteString getSnapshotBytes();
}
