// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/pubsub/v1/pubsub.proto
// Protobuf Java Version: 4.33.0

package com.google.pubsub.v1;

@com.google.protobuf.Generated
public interface DetachSubscriptionResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.DetachSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {}
