// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/pubsub/v1/pubsub.proto
// Protobuf Java Version: 4.33.0

package com.google.pubsub.v1;

@com.google.protobuf.Generated
public interface ListSnapshotsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListSnapshotsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>
   * repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  java.util.List<com.google.pubsub.v1.Snapshot> getSnapshotsList();

  /**
   *
   *
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>
   * repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  com.google.pubsub.v1.Snapshot getSnapshots(int index);

  /**
   *
   *
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>
   * repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  int getSnapshotsCount();

  /**
   *
   *
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>
   * repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  java.util.List<? extends com.google.pubsub.v1.SnapshotOrBuilder> getSnapshotsOrBuilderList();

  /**
   *
   *
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>
   * repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  com.google.pubsub.v1.SnapshotOrBuilder getSnapshotsOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Optional. If not empty, indicates that there may be more snapshot that
   * match the request; this value should be passed in a new
   * `ListSnapshotsRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();

  /**
   *
   *
   * <pre>
   * Optional. If not empty, indicates that there may be more snapshot that
   * match the request; this value should be passed in a new
   * `ListSnapshotsRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString getNextPageTokenBytes();
}
