// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/pubsub/v1/pubsub.proto
// Protobuf Java Version: 4.33.0

package com.google.pubsub.v1;

@com.google.protobuf.Generated
public interface ListTopicSubscriptionsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListTopicSubscriptionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Optional. The names of subscriptions attached to the topic specified in the
   * request.
   * </pre>
   *
   * <code>
   * repeated string subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return A list containing the subscriptions.
   */
  java.util.List<java.lang.String> getSubscriptionsList();

  /**
   *
   *
   * <pre>
   * Optional. The names of subscriptions attached to the topic specified in the
   * request.
   * </pre>
   *
   * <code>
   * repeated string subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The count of subscriptions.
   */
  int getSubscriptionsCount();

  /**
   *
   *
   * <pre>
   * Optional. The names of subscriptions attached to the topic specified in the
   * request.
   * </pre>
   *
   * <code>
   * repeated string subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @param index The index of the element to return.
   * @return The subscriptions at the given index.
   */
  java.lang.String getSubscriptions(int index);

  /**
   *
   *
   * <pre>
   * Optional. The names of subscriptions attached to the topic specified in the
   * request.
   * </pre>
   *
   * <code>
   * repeated string subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the subscriptions at the given index.
   */
  com.google.protobuf.ByteString getSubscriptionsBytes(int index);

  /**
   *
   *
   * <pre>
   * Optional. If not empty, indicates that there may be more subscriptions that
   * match the request; this value should be passed in a new
   * `ListTopicSubscriptionsRequest` to get more subscriptions.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();

  /**
   *
   *
   * <pre>
   * Optional. If not empty, indicates that there may be more subscriptions that
   * match the request; this value should be passed in a new
   * `ListTopicSubscriptionsRequest` to get more subscriptions.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString getNextPageTokenBytes();
}
