// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/pubsub/v1/pubsub.proto
// Protobuf Java Version: 4.33.0

package com.google.pubsub.v1;

@com.google.protobuf.Generated
public interface PublishResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.PublishResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Optional. The server-assigned ID of each published message, in the same
   * order as the messages in the request. IDs are guaranteed to be unique
   * within the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return A list containing the messageIds.
   */
  java.util.List<java.lang.String> getMessageIdsList();

  /**
   *
   *
   * <pre>
   * Optional. The server-assigned ID of each published message, in the same
   * order as the messages in the request. IDs are guaranteed to be unique
   * within the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The count of messageIds.
   */
  int getMessageIdsCount();

  /**
   *
   *
   * <pre>
   * Optional. The server-assigned ID of each published message, in the same
   * order as the messages in the request. IDs are guaranteed to be unique
   * within the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @param index The index of the element to return.
   * @return The messageIds at the given index.
   */
  java.lang.String getMessageIds(int index);

  /**
   *
   *
   * <pre>
   * Optional. The server-assigned ID of each published message, in the same
   * order as the messages in the request. IDs are guaranteed to be unique
   * within the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the messageIds at the given index.
   */
  com.google.protobuf.ByteString getMessageIdsBytes(int index);
}
