// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/pubsub/v1/schema.proto
// Protobuf Java Version: 4.33.0

package com.google.pubsub.v1;

@com.google.protobuf.Generated
public interface ValidateSchemaResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ValidateSchemaResponse)
    com.google.protobuf.MessageOrBuilder {}
