// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public interface DeleteTopicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.DeleteTopicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Name of the topic to delete.
   * Format is `projects/{project}/topics/{topic}`.
   * </pre>
   *
   * <code>string topic = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * Required. Name of the topic to delete.
   * Format is `projects/{project}/topics/{topic}`.
   * </pre>
   *
   * <code>string topic = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
