// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/schema.proto

package com.google.pubsub.v1;

public interface DeleteSchemaRevisionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.DeleteSchemaRevisionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The name of the schema revision to be deleted, with a revision ID
   * explicitly included.
   * Example: projects/123/schemas/my-schema&#64;c7cfa2a8
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. The name of the schema revision to be deleted, with a revision ID
   * explicitly included.
   * Example: projects/123/schemas/my-schema&#64;c7cfa2a8
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Required. The revision ID to roll back to.
   * It must be a revision of the same schema.
   *   Example: c7cfa2a8
   * </pre>
   *
   * <code>string revision_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The revisionId.
   */
  java.lang.String getRevisionId();
  /**
   * <pre>
   * Required. The revision ID to roll back to.
   * It must be a revision of the same schema.
   *   Example: c7cfa2a8
   * </pre>
   *
   * <code>string revision_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for revisionId.
   */
  com.google.protobuf.ByteString
      getRevisionIdBytes();
}
