// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public interface DetachSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.DetachSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {
}
