// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public interface GetSnapshotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.GetSnapshotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The name of the snapshot to get.
   * Format is `projects/{project}/snapshots/{snap}`.
   * </pre>
   *
   * <code>string snapshot = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The snapshot.
   */
  java.lang.String getSnapshot();
  /**
   * <pre>
   * Required. The name of the snapshot to get.
   * Format is `projects/{project}/snapshots/{snap}`.
   * </pre>
   *
   * <code>string snapshot = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for snapshot.
   */
  com.google.protobuf.ByteString
      getSnapshotBytes();
}
