// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

// Protobuf Java Version: 3.25.2
package com.google.pubsub.v1;

public interface IngestionDataSourceSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.IngestionDataSourceSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Amazon Kinesis Data Streams.
   * </pre>
   *
   * <code>.google.pubsub.v1.IngestionDataSourceSettings.AwsKinesis aws_kinesis = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the awsKinesis field is set.
   */
  boolean hasAwsKinesis();
  /**
   * <pre>
   * Optional. Amazon Kinesis Data Streams.
   * </pre>
   *
   * <code>.google.pubsub.v1.IngestionDataSourceSettings.AwsKinesis aws_kinesis = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The awsKinesis.
   */
  com.google.pubsub.v1.IngestionDataSourceSettings.AwsKinesis getAwsKinesis();
  /**
   * <pre>
   * Optional. Amazon Kinesis Data Streams.
   * </pre>
   *
   * <code>.google.pubsub.v1.IngestionDataSourceSettings.AwsKinesis aws_kinesis = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.IngestionDataSourceSettings.AwsKinesisOrBuilder getAwsKinesisOrBuilder();

  com.google.pubsub.v1.IngestionDataSourceSettings.SourceCase getSourceCase();
}
