// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/schema.proto

package com.google.pubsub.v1;

public interface ListSchemasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListSchemasResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resulting schemas.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Schema schemas = 1;</code>
   */
  java.util.List<com.google.pubsub.v1.Schema> 
      getSchemasList();
  /**
   * <pre>
   * The resulting schemas.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Schema schemas = 1;</code>
   */
  com.google.pubsub.v1.Schema getSchemas(int index);
  /**
   * <pre>
   * The resulting schemas.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Schema schemas = 1;</code>
   */
  int getSchemasCount();
  /**
   * <pre>
   * The resulting schemas.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Schema schemas = 1;</code>
   */
  java.util.List<? extends com.google.pubsub.v1.SchemaOrBuilder> 
      getSchemasOrBuilderList();
  /**
   * <pre>
   * The resulting schemas.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Schema schemas = 1;</code>
   */
  com.google.pubsub.v1.SchemaOrBuilder getSchemasOrBuilder(
      int index);

  /**
   * <pre>
   * If not empty, indicates that there may be more schemas that match the
   * request; this value should be passed in a new `ListSchemasRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * If not empty, indicates that there may be more schemas that match the
   * request; this value should be passed in a new `ListSchemasRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
