// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

// Protobuf Java Version: 3.25.3
package com.google.pubsub.v1;

public interface ListSnapshotsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListSnapshotsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<com.google.pubsub.v1.Snapshot> 
      getSnapshotsList();
  /**
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.Snapshot getSnapshots(int index);
  /**
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  int getSnapshotsCount();
  /**
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<? extends com.google.pubsub.v1.SnapshotOrBuilder> 
      getSnapshotsOrBuilderList();
  /**
   * <pre>
   * Optional. The resulting snapshots.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.SnapshotOrBuilder getSnapshotsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional. If not empty, indicates that there may be more snapshot that
   * match the request; this value should be passed in a new
   * `ListSnapshotsRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * Optional. If not empty, indicates that there may be more snapshot that
   * match the request; this value should be passed in a new
   * `ListSnapshotsRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
