// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

// Protobuf Java Version: 3.25.3
package com.google.pubsub.v1;

public interface ListTopicsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListTopicsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. The resulting topics.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Topic topics = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<com.google.pubsub.v1.Topic> 
      getTopicsList();
  /**
   * <pre>
   * Optional. The resulting topics.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Topic topics = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.Topic getTopics(int index);
  /**
   * <pre>
   * Optional. The resulting topics.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Topic topics = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  int getTopicsCount();
  /**
   * <pre>
   * Optional. The resulting topics.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Topic topics = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<? extends com.google.pubsub.v1.TopicOrBuilder> 
      getTopicsOrBuilderList();
  /**
   * <pre>
   * Optional. The resulting topics.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Topic topics = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.TopicOrBuilder getTopicsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional. If not empty, indicates that there may be more topics that match
   * the request; this value should be passed in a new `ListTopicsRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * Optional. If not empty, indicates that there may be more topics that match
   * the request; this value should be passed in a new `ListTopicsRequest`.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
