// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public interface ListTopicSnapshotsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListTopicSnapshotsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The names of the snapshots that match the request.
   * </pre>
   *
   * <code>repeated string snapshots = 1;</code>
   * @return A list containing the snapshots.
   */
  java.util.List<java.lang.String>
      getSnapshotsList();
  /**
   * <pre>
   * The names of the snapshots that match the request.
   * </pre>
   *
   * <code>repeated string snapshots = 1;</code>
   * @return The count of snapshots.
   */
  int getSnapshotsCount();
  /**
   * <pre>
   * The names of the snapshots that match the request.
   * </pre>
   *
   * <code>repeated string snapshots = 1;</code>
   * @param index The index of the element to return.
   * @return The snapshots at the given index.
   */
  java.lang.String getSnapshots(int index);
  /**
   * <pre>
   * The names of the snapshots that match the request.
   * </pre>
   *
   * <code>repeated string snapshots = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the snapshots at the given index.
   */
  com.google.protobuf.ByteString
      getSnapshotsBytes(int index);

  /**
   * <pre>
   * If not empty, indicates that there may be more snapshots that match
   * the request; this value should be passed in a new
   * `ListTopicSnapshotsRequest` to get more snapshots.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * If not empty, indicates that there may be more snapshots that match
   * the request; this value should be passed in a new
   * `ListTopicSnapshotsRequest` to get more snapshots.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
