// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

// Protobuf Java Version: 3.25.2
package com.google.pubsub.v1;

public interface ListSubscriptionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ListSubscriptionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. The subscriptions that match the request.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<com.google.pubsub.v1.Subscription> 
      getSubscriptionsList();
  /**
   * <pre>
   * Optional. The subscriptions that match the request.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.Subscription getSubscriptions(int index);
  /**
   * <pre>
   * Optional. The subscriptions that match the request.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  int getSubscriptionsCount();
  /**
   * <pre>
   * Optional. The subscriptions that match the request.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<? extends com.google.pubsub.v1.SubscriptionOrBuilder> 
      getSubscriptionsOrBuilderList();
  /**
   * <pre>
   * Optional. The subscriptions that match the request.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.SubscriptionOrBuilder getSubscriptionsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional. If not empty, indicates that there may be more subscriptions that
   * match the request; this value should be passed in a new
   * `ListSubscriptionsRequest` to get more subscriptions.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * Optional. If not empty, indicates that there may be more subscriptions that
   * match the request; this value should be passed in a new
   * `ListSubscriptionsRequest` to get more subscriptions.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
