// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public interface PublishResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.PublishResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The server-assigned ID of each published message, in the same order as
   * the messages in the request. IDs are guaranteed to be unique within
   * the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1;</code>
   * @return A list containing the messageIds.
   */
  java.util.List<java.lang.String>
      getMessageIdsList();
  /**
   * <pre>
   * The server-assigned ID of each published message, in the same order as
   * the messages in the request. IDs are guaranteed to be unique within
   * the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1;</code>
   * @return The count of messageIds.
   */
  int getMessageIdsCount();
  /**
   * <pre>
   * The server-assigned ID of each published message, in the same order as
   * the messages in the request. IDs are guaranteed to be unique within
   * the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The messageIds at the given index.
   */
  java.lang.String getMessageIds(int index);
  /**
   * <pre>
   * The server-assigned ID of each published message, in the same order as
   * the messages in the request. IDs are guaranteed to be unique within
   * the topic.
   * </pre>
   *
   * <code>repeated string message_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the messageIds at the given index.
   */
  com.google.protobuf.ByteString
      getMessageIdsBytes(int index);
}
