// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public final class PubsubProto {
  private PubsubProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_MessageStoragePolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_MessageStoragePolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_SchemaSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_SchemaSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_Topic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_Topic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_Topic_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_Topic_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PubsubMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PubsubMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PubsubMessage_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PubsubMessage_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_GetTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_GetTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_UpdateTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_UpdateTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PublishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListTopicsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListTopicsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListTopicsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListTopicsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListTopicSubscriptionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListTopicSubscriptionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListTopicSubscriptionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListTopicSubscriptionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListTopicSnapshotsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListTopicSnapshotsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListTopicSnapshotsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListTopicSnapshotsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_DeleteTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_DeleteTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_DetachSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_DetachSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_DetachSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_DetachSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_Subscription_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_Subscription_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_RetryPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_RetryPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_DeadLetterPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_DeadLetterPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ExpirationPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ExpirationPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PushConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PushConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PushConfig_OidcToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PushConfig_OidcToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PushConfig_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PushConfig_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_BigQueryConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_BigQueryConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ReceivedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ReceivedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_GetSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_GetSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_UpdateSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_UpdateSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListSubscriptionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListSubscriptionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListSubscriptionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListSubscriptionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_DeleteSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_DeleteSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ModifyPushConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ModifyPushConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PullRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PullRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_PullResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_PullResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ModifyAckDeadlineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ModifyAckDeadlineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_AcknowledgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_AcknowledgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_StreamingPullRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_StreamingPullRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_StreamingPullResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_StreamingPullResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_StreamingPullResponse_AcknowledgeConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_StreamingPullResponse_AcknowledgeConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_StreamingPullResponse_ModifyAckDeadlineConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_StreamingPullResponse_ModifyAckDeadlineConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_StreamingPullResponse_SubscriptionProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_StreamingPullResponse_SubscriptionProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_CreateSnapshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_CreateSnapshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_CreateSnapshotRequest_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_CreateSnapshotRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_UpdateSnapshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_UpdateSnapshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_Snapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_Snapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_Snapshot_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_Snapshot_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_GetSnapshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_GetSnapshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListSnapshotsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListSnapshotsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_ListSnapshotsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_ListSnapshotsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_DeleteSnapshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_DeleteSnapshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_SeekRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_SeekRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_pubsub_v1_SeekResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_pubsub_v1_SeekResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035google/pubsub/v1/pubsub.proto\022\020google." +
      "pubsub.v1\032\034google/api/annotations.proto\032" +
      "\027google/api/client.proto\032\037google/api/fie" +
      "ld_behavior.proto\032\031google/api/resource.p" +
      "roto\032\036google/protobuf/duration.proto\032\033go" +
      "ogle/protobuf/empty.proto\032 google/protob" +
      "uf/field_mask.proto\032\037google/protobuf/tim" +
      "estamp.proto\032\035google/pubsub/v1/schema.pr" +
      "oto\";\n\024MessageStoragePolicy\022#\n\033allowed_p" +
      "ersistence_regions\030\001 \003(\t\"t\n\016SchemaSettin" +
      "gs\0224\n\006schema\030\001 \001(\tB$\340A\002\372A\036\n\034pubsub.googl" +
      "eapis.com/Schema\022,\n\010encoding\030\002 \001(\0162\032.goo" +
      "gle.pubsub.v1.Encoding\"\303\003\n\005Topic\022\021\n\004name" +
      "\030\001 \001(\tB\003\340A\002\0223\n\006labels\030\002 \003(\0132#.google.pub" +
      "sub.v1.Topic.LabelsEntry\022F\n\026message_stor" +
      "age_policy\030\003 \001(\0132&.google.pubsub.v1.Mess" +
      "ageStoragePolicy\022\024\n\014kms_key_name\030\005 \001(\t\0229" +
      "\n\017schema_settings\030\006 \001(\0132 .google.pubsub." +
      "v1.SchemaSettings\022\025\n\rsatisfies_pzs\030\007 \001(\010" +
      "\022=\n\032message_retention_duration\030\010 \001(\0132\031.g" +
      "oogle.protobuf.Duration\032-\n\013LabelsEntry\022\013" +
      "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:T\352AQ\n\033pub" +
      "sub.googleapis.com/Topic\022!projects/{proj" +
      "ect}/topics/{topic}\022\017_deleted-topic_\"\361\001\n" +
      "\rPubsubMessage\022\014\n\004data\030\001 \001(\014\022C\n\nattribut" +
      "es\030\002 \003(\0132/.google.pubsub.v1.PubsubMessag" +
      "e.AttributesEntry\022\022\n\nmessage_id\030\003 \001(\t\0220\n" +
      "\014publish_time\030\004 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022\024\n\014ordering_key\030\005 \001(\t\0321\n\017Attribu" +
      "tesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "\"E\n\017GetTopicRequest\0222\n\005topic\030\001 \001(\tB#\340A\002\372" +
      "A\035\n\033pubsub.googleapis.com/Topic\"w\n\022Updat" +
      "eTopicRequest\022+\n\005topic\030\001 \001(\0132\027.google.pu" +
      "bsub.v1.TopicB\003\340A\002\0224\n\013update_mask\030\002 \001(\0132" +
      "\032.google.protobuf.FieldMaskB\003\340A\002\"|\n\016Publ" +
      "ishRequest\0222\n\005topic\030\001 \001(\tB#\340A\002\372A\035\n\033pubsu" +
      "b.googleapis.com/Topic\0226\n\010messages\030\002 \003(\013" +
      "2\037.google.pubsub.v1.PubsubMessageB\003\340A\002\"&" +
      "\n\017PublishResponse\022\023\n\013message_ids\030\001 \003(\t\"\200" +
      "\001\n\021ListTopicsRequest\022D\n\007project\030\001 \001(\tB3\340" +
      "A\002\372A-\n+cloudresourcemanager.googleapis.c" +
      "om/Project\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_to" +
      "ken\030\003 \001(\t\"V\n\022ListTopicsResponse\022\'\n\006topic" +
      "s\030\001 \003(\0132\027.google.pubsub.v1.Topic\022\027\n\017next" +
      "_page_token\030\002 \001(\t\"z\n\035ListTopicSubscripti" +
      "onsRequest\0222\n\005topic\030\001 \001(\tB#\340A\002\372A\035\n\033pubsu" +
      "b.googleapis.com/Topic\022\021\n\tpage_size\030\002 \001(" +
      "\005\022\022\n\npage_token\030\003 \001(\t\"y\n\036ListTopicSubscr" +
      "iptionsResponse\022>\n\rsubscriptions\030\001 \003(\tB\'" +
      "\372A$\n\"pubsub.googleapis.com/Subscription\022" +
      "\027\n\017next_page_token\030\002 \001(\t\"v\n\031ListTopicSna" +
      "pshotsRequest\0222\n\005topic\030\001 \001(\tB#\340A\002\372A\035\n\033pu" +
      "bsub.googleapis.com/Topic\022\021\n\tpage_size\030\002" +
      " \001(\005\022\022\n\npage_token\030\003 \001(\t\"H\n\032ListTopicSna" +
      "pshotsResponse\022\021\n\tsnapshots\030\001 \003(\t\022\027\n\017nex" +
      "t_page_token\030\002 \001(\t\"H\n\022DeleteTopicRequest" +
      "\0222\n\005topic\030\001 \001(\tB#\340A\002\372A\035\n\033pubsub.googleap" +
      "is.com/Topic\"]\n\031DetachSubscriptionReques" +
      "t\022@\n\014subscription\030\001 \001(\tB*\340A\002\372A$\n\"pubsub." +
      "googleapis.com/Subscription\"\034\n\032DetachSub" +
      "scriptionResponse\"\345\007\n\014Subscription\022\021\n\004na" +
      "me\030\001 \001(\tB\003\340A\002\0222\n\005topic\030\002 \001(\tB#\340A\002\372A\035\n\033pu" +
      "bsub.googleapis.com/Topic\0221\n\013push_config" +
      "\030\004 \001(\0132\034.google.pubsub.v1.PushConfig\0229\n\017" +
      "bigquery_config\030\022 \001(\0132 .google.pubsub.v1" +
      ".BigQueryConfig\022\034\n\024ack_deadline_seconds\030" +
      "\005 \001(\005\022\035\n\025retain_acked_messages\030\007 \001(\010\022=\n\032" +
      "message_retention_duration\030\010 \001(\0132\031.googl" +
      "e.protobuf.Duration\022:\n\006labels\030\t \003(\0132*.go" +
      "ogle.pubsub.v1.Subscription.LabelsEntry\022" +
      "\037\n\027enable_message_ordering\030\n \001(\010\022=\n\021expi" +
      "ration_policy\030\013 \001(\0132\".google.pubsub.v1.E" +
      "xpirationPolicy\022\016\n\006filter\030\014 \001(\t\022>\n\022dead_" +
      "letter_policy\030\r \001(\0132\".google.pubsub.v1.D" +
      "eadLetterPolicy\0223\n\014retry_policy\030\016 \001(\0132\035." +
      "google.pubsub.v1.RetryPolicy\022\020\n\010detached" +
      "\030\017 \001(\010\022$\n\034enable_exactly_once_delivery\030\020" +
      " \001(\010\022H\n topic_message_retention_duration" +
      "\030\021 \001(\0132\031.google.protobuf.DurationB\003\340A\003\0228" +
      "\n\005state\030\023 \001(\0162$.google.pubsub.v1.Subscri" +
      "ption.StateB\003\340A\003\032-\n\013LabelsEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\">\n\005State\022\025\n\021STAT" +
      "E_UNSPECIFIED\020\000\022\n\n\006ACTIVE\020\001\022\022\n\016RESOURCE_" +
      "ERROR\020\002:X\352AU\n\"pubsub.googleapis.com/Subs" +
      "cription\022/projects/{project}/subscriptio" +
      "ns/{subscription}\"u\n\013RetryPolicy\0222\n\017mini" +
      "mum_backoff\030\001 \001(\0132\031.google.protobuf.Dura" +
      "tion\0222\n\017maximum_backoff\030\002 \001(\0132\031.google.p" +
      "rotobuf.Duration\"L\n\020DeadLetterPolicy\022\031\n\021" +
      "dead_letter_topic\030\001 \001(\t\022\035\n\025max_delivery_" +
      "attempts\030\002 \001(\005\":\n\020ExpirationPolicy\022&\n\003tt" +
      "l\030\001 \001(\0132\031.google.protobuf.Duration\"\255\002\n\nP" +
      "ushConfig\022\025\n\rpush_endpoint\030\001 \001(\t\022@\n\nattr" +
      "ibutes\030\002 \003(\0132,.google.pubsub.v1.PushConf" +
      "ig.AttributesEntry\022<\n\noidc_token\030\003 \001(\0132&" +
      ".google.pubsub.v1.PushConfig.OidcTokenH\000" +
      "\032<\n\tOidcToken\022\035\n\025service_account_email\030\001" +
      " \001(\t\022\020\n\010audience\030\002 \001(\t\0321\n\017AttributesEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\027\n\025aut" +
      "hentication_method\"\221\002\n\016BigQueryConfig\022\r\n" +
      "\005table\030\001 \001(\t\022\030\n\020use_topic_schema\030\002 \001(\010\022\026" +
      "\n\016write_metadata\030\003 \001(\010\022\033\n\023drop_unknown_f" +
      "ields\030\004 \001(\010\022:\n\005state\030\005 \001(\0162&.google.pubs" +
      "ub.v1.BigQueryConfig.StateB\003\340A\003\"e\n\005State" +
      "\022\025\n\021STATE_UNSPECIFIED\020\000\022\n\n\006ACTIVE\020\001\022\025\n\021P" +
      "ERMISSION_DENIED\020\002\022\r\n\tNOT_FOUND\020\003\022\023\n\017SCH" +
      "EMA_MISMATCH\020\004\"m\n\017ReceivedMessage\022\016\n\006ack" +
      "_id\030\001 \001(\t\0220\n\007message\030\002 \001(\0132\037.google.pubs" +
      "ub.v1.PubsubMessage\022\030\n\020delivery_attempt\030" +
      "\003 \001(\005\"Z\n\026GetSubscriptionRequest\022@\n\014subsc" +
      "ription\030\001 \001(\tB*\340A\002\372A$\n\"pubsub.googleapis" +
      ".com/Subscription\"\214\001\n\031UpdateSubscription" +
      "Request\0229\n\014subscription\030\001 \001(\0132\036.google.p" +
      "ubsub.v1.SubscriptionB\003\340A\002\0224\n\013update_mas" +
      "k\030\002 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\002" +
      "\"\207\001\n\030ListSubscriptionsRequest\022D\n\007project" +
      "\030\001 \001(\tB3\340A\002\372A-\n+cloudresourcemanager.goo" +
      "gleapis.com/Project\022\021\n\tpage_size\030\002 \001(\005\022\022" +
      "\n\npage_token\030\003 \001(\t\"k\n\031ListSubscriptionsR" +
      "esponse\0225\n\rsubscriptions\030\001 \003(\0132\036.google." +
      "pubsub.v1.Subscription\022\027\n\017next_page_toke" +
      "n\030\002 \001(\t\"]\n\031DeleteSubscriptionRequest\022@\n\014" +
      "subscription\030\001 \001(\tB*\340A\002\372A$\n\"pubsub.googl" +
      "eapis.com/Subscription\"\223\001\n\027ModifyPushCon" +
      "figRequest\022@\n\014subscription\030\001 \001(\tB*\340A\002\372A$" +
      "\n\"pubsub.googleapis.com/Subscription\0226\n\013" +
      "push_config\030\002 \001(\0132\034.google.pubsub.v1.Pus" +
      "hConfigB\003\340A\002\"\215\001\n\013PullRequest\022@\n\014subscrip" +
      "tion\030\001 \001(\tB*\340A\002\372A$\n\"pubsub.googleapis.co" +
      "m/Subscription\022!\n\022return_immediately\030\002 \001" +
      "(\010B\005\030\001\340A\001\022\031\n\014max_messages\030\003 \001(\005B\003\340A\002\"L\n\014" +
      "PullResponse\022<\n\021received_messages\030\001 \003(\0132" +
      "!.google.pubsub.v1.ReceivedMessage\"\225\001\n\030M" +
      "odifyAckDeadlineRequest\022@\n\014subscription\030" +
      "\001 \001(\tB*\340A\002\372A$\n\"pubsub.googleapis.com/Sub" +
      "scription\022\024\n\007ack_ids\030\004 \003(\tB\003\340A\002\022!\n\024ack_d" +
      "eadline_seconds\030\003 \001(\005B\003\340A\002\"l\n\022Acknowledg" +
      "eRequest\022@\n\014subscription\030\001 \001(\tB*\340A\002\372A$\n\"" +
      "pubsub.googleapis.com/Subscription\022\024\n\007ac" +
      "k_ids\030\002 \003(\tB\003\340A\002\"\251\002\n\024StreamingPullReques" +
      "t\022@\n\014subscription\030\001 \001(\tB*\340A\002\372A$\n\"pubsub." +
      "googleapis.com/Subscription\022\017\n\007ack_ids\030\002" +
      " \003(\t\022\037\n\027modify_deadline_seconds\030\003 \003(\005\022\037\n" +
      "\027modify_deadline_ack_ids\030\004 \003(\t\022(\n\033stream" +
      "_ack_deadline_seconds\030\005 \001(\005B\003\340A\002\022\021\n\tclie" +
      "nt_id\030\006 \001(\t\022 \n\030max_outstanding_messages\030" +
      "\007 \001(\003\022\035\n\025max_outstanding_bytes\030\010 \001(\003\"\236\005\n" +
      "\025StreamingPullResponse\022<\n\021received_messa" +
      "ges\030\001 \003(\0132!.google.pubsub.v1.ReceivedMes" +
      "sage\022a\n\030acknowledge_confirmation\030\005 \001(\0132?" +
      ".google.pubsub.v1.StreamingPullResponse." +
      "AcknowledgeConfirmation\022o\n modify_ack_de" +
      "adline_confirmation\030\003 \001(\0132E.google.pubsu" +
      "b.v1.StreamingPullResponse.ModifyAckDead" +
      "lineConfirmation\022_\n\027subscription_propert" +
      "ies\030\004 \001(\0132>.google.pubsub.v1.StreamingPu" +
      "llResponse.SubscriptionProperties\032^\n\027Ack" +
      "nowledgeConfirmation\022\017\n\007ack_ids\030\001 \003(\t\022\027\n" +
      "\017invalid_ack_ids\030\002 \003(\t\022\031\n\021unordered_ack_" +
      "ids\030\003 \003(\t\032I\n\035ModifyAckDeadlineConfirmati" +
      "on\022\017\n\007ack_ids\030\001 \003(\t\022\027\n\017invalid_ack_ids\030\002" +
      " \003(\t\032a\n\026SubscriptionProperties\022%\n\035exactl" +
      "y_once_delivery_enabled\030\001 \001(\010\022 \n\030message" +
      "_ordering_enabled\030\002 \001(\010J\004\010\002\020\003\"\203\002\n\025Create" +
      "SnapshotRequest\0224\n\004name\030\001 \001(\tB&\340A\002\372A \n\036p" +
      "ubsub.googleapis.com/Snapshot\022@\n\014subscri" +
      "ption\030\002 \001(\tB*\340A\002\372A$\n\"pubsub.googleapis.c" +
      "om/Subscription\022C\n\006labels\030\003 \003(\01323.google" +
      ".pubsub.v1.CreateSnapshotRequest.LabelsE" +
      "ntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"\200\001\n\025UpdateSnapshotRequest\0221\n" +
      "\010snapshot\030\001 \001(\0132\032.google.pubsub.v1.Snaps" +
      "hotB\003\340A\002\0224\n\013update_mask\030\002 \001(\0132\032.google.p" +
      "rotobuf.FieldMaskB\003\340A\002\"\257\002\n\010Snapshot\022\014\n\004n" +
      "ame\030\001 \001(\t\022/\n\005topic\030\002 \001(\tB \372A\035\n\033pubsub.go" +
      "ogleapis.com/Topic\022/\n\013expire_time\030\003 \001(\0132" +
      "\032.google.protobuf.Timestamp\0226\n\006labels\030\004 " +
      "\003(\0132&.google.pubsub.v1.Snapshot.LabelsEn" +
      "try\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001:L\352AI\n\036pubsub.googleapis.com/S" +
      "napshot\022\'projects/{project}/snapshots/{s" +
      "napshot}\"N\n\022GetSnapshotRequest\0228\n\010snapsh" +
      "ot\030\001 \001(\tB&\340A\002\372A \n\036pubsub.googleapis.com/" +
      "Snapshot\"\203\001\n\024ListSnapshotsRequest\022D\n\007pro" +
      "ject\030\001 \001(\tB3\340A\002\372A-\n+cloudresourcemanager" +
      ".googleapis.com/Project\022\021\n\tpage_size\030\002 \001" +
      "(\005\022\022\n\npage_token\030\003 \001(\t\"_\n\025ListSnapshotsR" +
      "esponse\022-\n\tsnapshots\030\001 \003(\0132\032.google.pubs" +
      "ub.v1.Snapshot\022\027\n\017next_page_token\030\002 \001(\t\"" +
      "Q\n\025DeleteSnapshotRequest\0228\n\010snapshot\030\001 \001" +
      "(\tB&\340A\002\372A \n\036pubsub.googleapis.com/Snapsh" +
      "ot\"\276\001\n\013SeekRequest\022@\n\014subscription\030\001 \001(\t" +
      "B*\340A\002\372A$\n\"pubsub.googleapis.com/Subscrip" +
      "tion\022*\n\004time\030\002 \001(\0132\032.google.protobuf.Tim" +
      "estampH\000\0227\n\010snapshot\030\003 \001(\tB#\372A \n\036pubsub." +
      "googleapis.com/SnapshotH\000B\010\n\006target\"\016\n\014S" +
      "eekResponse2\243\013\n\tPublisher\022q\n\013CreateTopic" +
      "\022\027.google.pubsub.v1.Topic\032\027.google.pubsu" +
      "b.v1.Topic\"0\202\323\344\223\002#\032\036/v1/{name=projects/*" +
      "/topics/*}:\001*\332A\004name\022}\n\013UpdateTopic\022$.go" +
      "ogle.pubsub.v1.UpdateTopicRequest\032\027.goog" +
      "le.pubsub.v1.Topic\"/\202\323\344\223\002)2$/v1/{topic.n" +
      "ame=projects/*/topics/*}:\001*\022\223\001\n\007Publish\022" +
      " .google.pubsub.v1.PublishRequest\032!.goog" +
      "le.pubsub.v1.PublishResponse\"C\202\323\344\223\002,\"\'/v" +
      "1/{topic=projects/*/topics/*}:publish:\001*" +
      "\332A\016topic,messages\022w\n\010GetTopic\022!.google.p" +
      "ubsub.v1.GetTopicRequest\032\027.google.pubsub" +
      ".v1.Topic\"/\202\323\344\223\002!\022\037/v1/{topic=projects/*" +
      "/topics/*}\332A\005topic\022\212\001\n\nListTopics\022#.goog" +
      "le.pubsub.v1.ListTopicsRequest\032$.google." +
      "pubsub.v1.ListTopicsResponse\"1\202\323\344\223\002!\022\037/v" +
      "1/{project=projects/*}/topics\332A\007project\022" +
      "\272\001\n\026ListTopicSubscriptions\022/.google.pubs" +
      "ub.v1.ListTopicSubscriptionsRequest\0320.go" +
      "ogle.pubsub.v1.ListTopicSubscriptionsRes" +
      "ponse\"=\202\323\344\223\002/\022-/v1/{topic=projects/*/top" +
      "ics/*}/subscriptions\332A\005topic\022\252\001\n\022ListTop" +
      "icSnapshots\022+.google.pubsub.v1.ListTopic" +
      "SnapshotsRequest\032,.google.pubsub.v1.List" +
      "TopicSnapshotsResponse\"9\202\323\344\223\002+\022)/v1/{top" +
      "ic=projects/*/topics/*}/snapshots\332A\005topi" +
      "c\022|\n\013DeleteTopic\022$.google.pubsub.v1.Dele" +
      "teTopicRequest\032\026.google.protobuf.Empty\"/" +
      "\202\323\344\223\002!*\037/v1/{topic=projects/*/topics/*}\332" +
      "A\005topic\022\255\001\n\022DetachSubscription\022+.google." +
      "pubsub.v1.DetachSubscriptionRequest\032,.go" +
      "ogle.pubsub.v1.DetachSubscriptionRespons" +
      "e\"<\202\323\344\223\0026\"4/v1/{subscription=projects/*/" +
      "subscriptions/*}:detach\032p\312A\025pubsub.googl" +
      "eapis.com\322AUhttps://www.googleapis.com/a" +
      "uth/cloud-platform,https://www.googleapi" +
      "s.com/auth/pubsub2\240\025\n\nSubscriber\022\264\001\n\022Cre" +
      "ateSubscription\022\036.google.pubsub.v1.Subsc" +
      "ription\032\036.google.pubsub.v1.Subscription\"" +
      "^\202\323\344\223\002*\032%/v1/{name=projects/*/subscripti" +
      "ons/*}:\001*\332A+name,topic,push_config,ack_d" +
      "eadline_seconds\022\241\001\n\017GetSubscription\022(.go" +
      "ogle.pubsub.v1.GetSubscriptionRequest\032\036." +
      "google.pubsub.v1.Subscription\"D\202\323\344\223\002/\022-/" +
      "v1/{subscription=projects/*/subscription" +
      "s/*}\332A\014subscription\022\240\001\n\022UpdateSubscripti" +
      "on\022+.google.pubsub.v1.UpdateSubscription" +
      "Request\032\036.google.pubsub.v1.Subscription\"" +
      "=\202\323\344\223\002722/v1/{subscription.name=projects" +
      "/*/subscriptions/*}:\001*\022\246\001\n\021ListSubscript" +
      "ions\022*.google.pubsub.v1.ListSubscription" +
      "sRequest\032+.google.pubsub.v1.ListSubscrip" +
      "tionsResponse\"8\202\323\344\223\002(\022&/v1/{project=proj" +
      "ects/*}/subscriptions\332A\007project\022\237\001\n\022Dele" +
      "teSubscription\022+.google.pubsub.v1.Delete" +
      "SubscriptionRequest\032\026.google.protobuf.Em" +
      "pty\"D\202\323\344\223\002/*-/v1/{subscription=projects/" +
      "*/subscriptions/*}\332A\014subscription\022\317\001\n\021Mo" +
      "difyAckDeadline\022*.google.pubsub.v1.Modif" +
      "yAckDeadlineRequest\032\026.google.protobuf.Em" +
      "pty\"v\202\323\344\223\002D\"?/v1/{subscription=projects/" +
      "*/subscriptions/*}:modifyAckDeadline:\001*\332" +
      "A)subscription,ack_ids,ack_deadline_seco" +
      "nds\022\250\001\n\013Acknowledge\022$.google.pubsub.v1.A" +
      "cknowledgeRequest\032\026.google.protobuf.Empt" +
      "y\"[\202\323\344\223\002>\"9/v1/{subscription=projects/*/" +
      "subscriptions/*}:acknowledge:\001*\332A\024subscr" +
      "iption,ack_ids\022\320\001\n\004Pull\022\035.google.pubsub." +
      "v1.PullRequest\032\036.google.pubsub.v1.PullRe" +
      "sponse\"\210\001\202\323\344\223\0027\"2/v1/{subscription=proje" +
      "cts/*/subscriptions/*}:pull:\001*\332A,subscri" +
      "ption,return_immediately,max_messages\332A\031" +
      "subscription,max_messages\022f\n\rStreamingPu" +
      "ll\022&.google.pubsub.v1.StreamingPullReque" +
      "st\032\'.google.pubsub.v1.StreamingPullRespo" +
      "nse\"\000(\0010\001\022\273\001\n\020ModifyPushConfig\022).google." +
      "pubsub.v1.ModifyPushConfigRequest\032\026.goog" +
      "le.protobuf.Empty\"d\202\323\344\223\002C\">/v1/{subscrip" +
      "tion=projects/*/subscriptions/*}:modifyP" +
      "ushConfig:\001*\332A\030subscription,push_config\022" +
      "\211\001\n\013GetSnapshot\022$.google.pubsub.v1.GetSn" +
      "apshotRequest\032\032.google.pubsub.v1.Snapsho" +
      "t\"8\202\323\344\223\002\'\022%/v1/{snapshot=projects/*/snap" +
      "shots/*}\332A\010snapshot\022\226\001\n\rListSnapshots\022&." +
      "google.pubsub.v1.ListSnapshotsRequest\032\'." +
      "google.pubsub.v1.ListSnapshotsResponse\"4" +
      "\202\323\344\223\002$\022\"/v1/{project=projects/*}/snapsho" +
      "ts\332A\007project\022\227\001\n\016CreateSnapshot\022\'.google" +
      ".pubsub.v1.CreateSnapshotRequest\032\032.googl" +
      "e.pubsub.v1.Snapshot\"@\202\323\344\223\002&\032!/v1/{name=" +
      "projects/*/snapshots/*}:\001*\332A\021name,subscr" +
      "iption\022\214\001\n\016UpdateSnapshot\022\'.google.pubsu" +
      "b.v1.UpdateSnapshotRequest\032\032.google.pubs" +
      "ub.v1.Snapshot\"5\202\323\344\223\002/2*/v1/{snapshot.na" +
      "me=projects/*/snapshots/*}:\001*\022\213\001\n\016Delete" +
      "Snapshot\022\'.google.pubsub.v1.DeleteSnapsh" +
      "otRequest\032\026.google.protobuf.Empty\"8\202\323\344\223\002" +
      "\'*%/v1/{snapshot=projects/*/snapshots/*}" +
      "\332A\010snapshot\022\204\001\n\004Seek\022\035.google.pubsub.v1." +
      "SeekRequest\032\036.google.pubsub.v1.SeekRespo" +
      "nse\"=\202\323\344\223\0027\"2/v1/{subscription=projects/" +
      "*/subscriptions/*}:seek:\001*\032p\312A\025pubsub.go" +
      "ogleapis.com\322AUhttps://www.googleapis.co" +
      "m/auth/cloud-platform,https://www.google" +
      "apis.com/auth/pubsubB\256\001\n\024com.google.pubs" +
      "ub.v1B\013PubsubProtoP\001Z6google.golang.org/" +
      "genproto/googleapis/pubsub/v1;pubsub\370\001\001\252" +
      "\002\026Google.Cloud.PubSub.V1\312\002\026Google\\Cloud\\" +
      "PubSub\\V1\352\002\031Google::Cloud::PubSub::V1b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.pubsub.v1.SchemaProto.getDescriptor(),
        });
    internal_static_google_pubsub_v1_MessageStoragePolicy_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_pubsub_v1_MessageStoragePolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_MessageStoragePolicy_descriptor,
        new java.lang.String[] { "AllowedPersistenceRegions", });
    internal_static_google_pubsub_v1_SchemaSettings_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_pubsub_v1_SchemaSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_SchemaSettings_descriptor,
        new java.lang.String[] { "Schema", "Encoding", });
    internal_static_google_pubsub_v1_Topic_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_pubsub_v1_Topic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_Topic_descriptor,
        new java.lang.String[] { "Name", "Labels", "MessageStoragePolicy", "KmsKeyName", "SchemaSettings", "SatisfiesPzs", "MessageRetentionDuration", });
    internal_static_google_pubsub_v1_Topic_LabelsEntry_descriptor =
      internal_static_google_pubsub_v1_Topic_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_Topic_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_Topic_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_pubsub_v1_PubsubMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_pubsub_v1_PubsubMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PubsubMessage_descriptor,
        new java.lang.String[] { "Data", "Attributes", "MessageId", "PublishTime", "OrderingKey", });
    internal_static_google_pubsub_v1_PubsubMessage_AttributesEntry_descriptor =
      internal_static_google_pubsub_v1_PubsubMessage_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_PubsubMessage_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PubsubMessage_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_pubsub_v1_GetTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_pubsub_v1_GetTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_GetTopicRequest_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_google_pubsub_v1_UpdateTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_pubsub_v1_UpdateTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_UpdateTopicRequest_descriptor,
        new java.lang.String[] { "Topic", "UpdateMask", });
    internal_static_google_pubsub_v1_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_pubsub_v1_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PublishRequest_descriptor,
        new java.lang.String[] { "Topic", "Messages", });
    internal_static_google_pubsub_v1_PublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_pubsub_v1_PublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PublishResponse_descriptor,
        new java.lang.String[] { "MessageIds", });
    internal_static_google_pubsub_v1_ListTopicsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_pubsub_v1_ListTopicsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListTopicsRequest_descriptor,
        new java.lang.String[] { "Project", "PageSize", "PageToken", });
    internal_static_google_pubsub_v1_ListTopicsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_pubsub_v1_ListTopicsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListTopicsResponse_descriptor,
        new java.lang.String[] { "Topics", "NextPageToken", });
    internal_static_google_pubsub_v1_ListTopicSubscriptionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_pubsub_v1_ListTopicSubscriptionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListTopicSubscriptionsRequest_descriptor,
        new java.lang.String[] { "Topic", "PageSize", "PageToken", });
    internal_static_google_pubsub_v1_ListTopicSubscriptionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_pubsub_v1_ListTopicSubscriptionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListTopicSubscriptionsResponse_descriptor,
        new java.lang.String[] { "Subscriptions", "NextPageToken", });
    internal_static_google_pubsub_v1_ListTopicSnapshotsRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_pubsub_v1_ListTopicSnapshotsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListTopicSnapshotsRequest_descriptor,
        new java.lang.String[] { "Topic", "PageSize", "PageToken", });
    internal_static_google_pubsub_v1_ListTopicSnapshotsResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_pubsub_v1_ListTopicSnapshotsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListTopicSnapshotsResponse_descriptor,
        new java.lang.String[] { "Snapshots", "NextPageToken", });
    internal_static_google_pubsub_v1_DeleteTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_pubsub_v1_DeleteTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_DeleteTopicRequest_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_google_pubsub_v1_DetachSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_pubsub_v1_DetachSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_DetachSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_google_pubsub_v1_DetachSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_pubsub_v1_DetachSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_DetachSubscriptionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_pubsub_v1_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_pubsub_v1_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_Subscription_descriptor,
        new java.lang.String[] { "Name", "Topic", "PushConfig", "BigqueryConfig", "AckDeadlineSeconds", "RetainAckedMessages", "MessageRetentionDuration", "Labels", "EnableMessageOrdering", "ExpirationPolicy", "Filter", "DeadLetterPolicy", "RetryPolicy", "Detached", "EnableExactlyOnceDelivery", "TopicMessageRetentionDuration", "State", });
    internal_static_google_pubsub_v1_Subscription_LabelsEntry_descriptor =
      internal_static_google_pubsub_v1_Subscription_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_Subscription_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_Subscription_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_pubsub_v1_RetryPolicy_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_pubsub_v1_RetryPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_RetryPolicy_descriptor,
        new java.lang.String[] { "MinimumBackoff", "MaximumBackoff", });
    internal_static_google_pubsub_v1_DeadLetterPolicy_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_pubsub_v1_DeadLetterPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_DeadLetterPolicy_descriptor,
        new java.lang.String[] { "DeadLetterTopic", "MaxDeliveryAttempts", });
    internal_static_google_pubsub_v1_ExpirationPolicy_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_pubsub_v1_ExpirationPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ExpirationPolicy_descriptor,
        new java.lang.String[] { "Ttl", });
    internal_static_google_pubsub_v1_PushConfig_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_pubsub_v1_PushConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PushConfig_descriptor,
        new java.lang.String[] { "PushEndpoint", "Attributes", "OidcToken", "AuthenticationMethod", });
    internal_static_google_pubsub_v1_PushConfig_OidcToken_descriptor =
      internal_static_google_pubsub_v1_PushConfig_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_PushConfig_OidcToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PushConfig_OidcToken_descriptor,
        new java.lang.String[] { "ServiceAccountEmail", "Audience", });
    internal_static_google_pubsub_v1_PushConfig_AttributesEntry_descriptor =
      internal_static_google_pubsub_v1_PushConfig_descriptor.getNestedTypes().get(1);
    internal_static_google_pubsub_v1_PushConfig_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PushConfig_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_pubsub_v1_BigQueryConfig_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_pubsub_v1_BigQueryConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_BigQueryConfig_descriptor,
        new java.lang.String[] { "Table", "UseTopicSchema", "WriteMetadata", "DropUnknownFields", "State", });
    internal_static_google_pubsub_v1_ReceivedMessage_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_pubsub_v1_ReceivedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ReceivedMessage_descriptor,
        new java.lang.String[] { "AckId", "Message", "DeliveryAttempt", });
    internal_static_google_pubsub_v1_GetSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_pubsub_v1_GetSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_GetSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_google_pubsub_v1_UpdateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_pubsub_v1_UpdateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_UpdateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", "UpdateMask", });
    internal_static_google_pubsub_v1_ListSubscriptionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_google_pubsub_v1_ListSubscriptionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListSubscriptionsRequest_descriptor,
        new java.lang.String[] { "Project", "PageSize", "PageToken", });
    internal_static_google_pubsub_v1_ListSubscriptionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_google_pubsub_v1_ListSubscriptionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListSubscriptionsResponse_descriptor,
        new java.lang.String[] { "Subscriptions", "NextPageToken", });
    internal_static_google_pubsub_v1_DeleteSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_google_pubsub_v1_DeleteSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_DeleteSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_google_pubsub_v1_ModifyPushConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_google_pubsub_v1_ModifyPushConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ModifyPushConfigRequest_descriptor,
        new java.lang.String[] { "Subscription", "PushConfig", });
    internal_static_google_pubsub_v1_PullRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_google_pubsub_v1_PullRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PullRequest_descriptor,
        new java.lang.String[] { "Subscription", "ReturnImmediately", "MaxMessages", });
    internal_static_google_pubsub_v1_PullResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_google_pubsub_v1_PullResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_PullResponse_descriptor,
        new java.lang.String[] { "ReceivedMessages", });
    internal_static_google_pubsub_v1_ModifyAckDeadlineRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_google_pubsub_v1_ModifyAckDeadlineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ModifyAckDeadlineRequest_descriptor,
        new java.lang.String[] { "Subscription", "AckIds", "AckDeadlineSeconds", });
    internal_static_google_pubsub_v1_AcknowledgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_google_pubsub_v1_AcknowledgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_AcknowledgeRequest_descriptor,
        new java.lang.String[] { "Subscription", "AckIds", });
    internal_static_google_pubsub_v1_StreamingPullRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_google_pubsub_v1_StreamingPullRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_StreamingPullRequest_descriptor,
        new java.lang.String[] { "Subscription", "AckIds", "ModifyDeadlineSeconds", "ModifyDeadlineAckIds", "StreamAckDeadlineSeconds", "ClientId", "MaxOutstandingMessages", "MaxOutstandingBytes", });
    internal_static_google_pubsub_v1_StreamingPullResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_google_pubsub_v1_StreamingPullResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_StreamingPullResponse_descriptor,
        new java.lang.String[] { "ReceivedMessages", "AcknowledgeConfirmation", "ModifyAckDeadlineConfirmation", "SubscriptionProperties", });
    internal_static_google_pubsub_v1_StreamingPullResponse_AcknowledgeConfirmation_descriptor =
      internal_static_google_pubsub_v1_StreamingPullResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_StreamingPullResponse_AcknowledgeConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_StreamingPullResponse_AcknowledgeConfirmation_descriptor,
        new java.lang.String[] { "AckIds", "InvalidAckIds", "UnorderedAckIds", });
    internal_static_google_pubsub_v1_StreamingPullResponse_ModifyAckDeadlineConfirmation_descriptor =
      internal_static_google_pubsub_v1_StreamingPullResponse_descriptor.getNestedTypes().get(1);
    internal_static_google_pubsub_v1_StreamingPullResponse_ModifyAckDeadlineConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_StreamingPullResponse_ModifyAckDeadlineConfirmation_descriptor,
        new java.lang.String[] { "AckIds", "InvalidAckIds", });
    internal_static_google_pubsub_v1_StreamingPullResponse_SubscriptionProperties_descriptor =
      internal_static_google_pubsub_v1_StreamingPullResponse_descriptor.getNestedTypes().get(2);
    internal_static_google_pubsub_v1_StreamingPullResponse_SubscriptionProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_StreamingPullResponse_SubscriptionProperties_descriptor,
        new java.lang.String[] { "ExactlyOnceDeliveryEnabled", "MessageOrderingEnabled", });
    internal_static_google_pubsub_v1_CreateSnapshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_google_pubsub_v1_CreateSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_CreateSnapshotRequest_descriptor,
        new java.lang.String[] { "Name", "Subscription", "Labels", });
    internal_static_google_pubsub_v1_CreateSnapshotRequest_LabelsEntry_descriptor =
      internal_static_google_pubsub_v1_CreateSnapshotRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_CreateSnapshotRequest_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_CreateSnapshotRequest_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_pubsub_v1_UpdateSnapshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_google_pubsub_v1_UpdateSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_UpdateSnapshotRequest_descriptor,
        new java.lang.String[] { "Snapshot", "UpdateMask", });
    internal_static_google_pubsub_v1_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_google_pubsub_v1_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_Snapshot_descriptor,
        new java.lang.String[] { "Name", "Topic", "ExpireTime", "Labels", });
    internal_static_google_pubsub_v1_Snapshot_LabelsEntry_descriptor =
      internal_static_google_pubsub_v1_Snapshot_descriptor.getNestedTypes().get(0);
    internal_static_google_pubsub_v1_Snapshot_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_Snapshot_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_pubsub_v1_GetSnapshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_google_pubsub_v1_GetSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_GetSnapshotRequest_descriptor,
        new java.lang.String[] { "Snapshot", });
    internal_static_google_pubsub_v1_ListSnapshotsRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_google_pubsub_v1_ListSnapshotsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListSnapshotsRequest_descriptor,
        new java.lang.String[] { "Project", "PageSize", "PageToken", });
    internal_static_google_pubsub_v1_ListSnapshotsResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_google_pubsub_v1_ListSnapshotsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_ListSnapshotsResponse_descriptor,
        new java.lang.String[] { "Snapshots", "NextPageToken", });
    internal_static_google_pubsub_v1_DeleteSnapshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_google_pubsub_v1_DeleteSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_DeleteSnapshotRequest_descriptor,
        new java.lang.String[] { "Snapshot", });
    internal_static_google_pubsub_v1_SeekRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_google_pubsub_v1_SeekRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_SeekRequest_descriptor,
        new java.lang.String[] { "Subscription", "Time", "Snapshot", "Target", });
    internal_static_google_pubsub_v1_SeekResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_google_pubsub_v1_SeekResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_pubsub_v1_SeekResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.pubsub.v1.SchemaProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
