// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

// Protobuf Java Version: 3.25.3
package com.google.pubsub.v1;

public interface PullResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.PullResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Received Pub/Sub messages. The list will be empty if there are no
   * more messages available in the backlog, or if no messages could be returned
   * before the request timeout. For JSON, the response can be entirely
   * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
   * even if there are more messages available in the backlog.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<com.google.pubsub.v1.ReceivedMessage> 
      getReceivedMessagesList();
  /**
   * <pre>
   * Optional. Received Pub/Sub messages. The list will be empty if there are no
   * more messages available in the backlog, or if no messages could be returned
   * before the request timeout. For JSON, the response can be entirely
   * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
   * even if there are more messages available in the backlog.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.ReceivedMessage getReceivedMessages(int index);
  /**
   * <pre>
   * Optional. Received Pub/Sub messages. The list will be empty if there are no
   * more messages available in the backlog, or if no messages could be returned
   * before the request timeout. For JSON, the response can be entirely
   * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
   * even if there are more messages available in the backlog.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  int getReceivedMessagesCount();
  /**
   * <pre>
   * Optional. Received Pub/Sub messages. The list will be empty if there are no
   * more messages available in the backlog, or if no messages could be returned
   * before the request timeout. For JSON, the response can be entirely
   * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
   * even if there are more messages available in the backlog.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  java.util.List<? extends com.google.pubsub.v1.ReceivedMessageOrBuilder> 
      getReceivedMessagesOrBuilderList();
  /**
   * <pre>
   * Optional. Received Pub/Sub messages. The list will be empty if there are no
   * more messages available in the backlog, or if no messages could be returned
   * before the request timeout. For JSON, the response can be entirely
   * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
   * even if there are more messages available in the backlog.
   * </pre>
   *
   * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.pubsub.v1.ReceivedMessageOrBuilder getReceivedMessagesOrBuilder(
      int index);
}
