// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

public interface RetryPolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.RetryPolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The minimum delay between consecutive deliveries of a given message.
   * Value should be between 0 and 600 seconds. Defaults to 10 seconds.
   * </pre>
   *
   * <code>.google.protobuf.Duration minimum_backoff = 1;</code>
   * @return Whether the minimumBackoff field is set.
   */
  boolean hasMinimumBackoff();
  /**
   * <pre>
   * The minimum delay between consecutive deliveries of a given message.
   * Value should be between 0 and 600 seconds. Defaults to 10 seconds.
   * </pre>
   *
   * <code>.google.protobuf.Duration minimum_backoff = 1;</code>
   * @return The minimumBackoff.
   */
  com.google.protobuf.Duration getMinimumBackoff();
  /**
   * <pre>
   * The minimum delay between consecutive deliveries of a given message.
   * Value should be between 0 and 600 seconds. Defaults to 10 seconds.
   * </pre>
   *
   * <code>.google.protobuf.Duration minimum_backoff = 1;</code>
   */
  com.google.protobuf.DurationOrBuilder getMinimumBackoffOrBuilder();

  /**
   * <pre>
   * The maximum delay between consecutive deliveries of a given message.
   * Value should be between 0 and 600 seconds. Defaults to 600 seconds.
   * </pre>
   *
   * <code>.google.protobuf.Duration maximum_backoff = 2;</code>
   * @return Whether the maximumBackoff field is set.
   */
  boolean hasMaximumBackoff();
  /**
   * <pre>
   * The maximum delay between consecutive deliveries of a given message.
   * Value should be between 0 and 600 seconds. Defaults to 600 seconds.
   * </pre>
   *
   * <code>.google.protobuf.Duration maximum_backoff = 2;</code>
   * @return The maximumBackoff.
   */
  com.google.protobuf.Duration getMaximumBackoff();
  /**
   * <pre>
   * The maximum delay between consecutive deliveries of a given message.
   * Value should be between 0 and 600 seconds. Defaults to 600 seconds.
   * </pre>
   *
   * <code>.google.protobuf.Duration maximum_backoff = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getMaximumBackoffOrBuilder();
}
