// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

// Protobuf Java Version: 3.25.3
package com.google.pubsub.v1;

public interface SeekResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.SeekResponse)
    com.google.protobuf.MessageOrBuilder {
}
