// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/schema.proto

// Protobuf Java Version: 3.25.3
package com.google.pubsub.v1;

public interface ValidateMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ValidateMessageResponse)
    com.google.protobuf.MessageOrBuilder {
}
