// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/pubsub/v1/schema.proto

// Protobuf Java Version: 3.25.2
package com.google.pubsub.v1;

public interface ValidateSchemaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.pubsub.v1.ValidateSchemaResponse)
    com.google.protobuf.MessageOrBuilder {
}
