on:
  push:
    branches:
    - master
  pull_request:
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [7, 8, 11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: test
    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        name: actions ${{matrix.java}}
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - run: .kokoro/build.bat
      env:
        JOB_TYPE: test
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - run: java -version
    - run: .kokoro/dependencies.sh
  linkage-monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - name: Install artifacts to local Maven repository
      run: |
        source .kokoro/common.sh
        retry_with_backoff 3 10 \
            mvn install -B -V \
                -Dmaven.test.skip -DskipTests=true \
                -Dclirr.skip=true \
                -Denforcer.skip=true \
                -Dmaven.javadoc.skip=true \
                -Dgcloud.download.skip=true
      shell: bash
    - uses: GoogleCloudPlatform/cloud-opensource-java/linkage-monitor@v1-linkagemonitor
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: lint
  clirr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: clirr